### ISSUE TITLE
Heroku app not deploying due to missing dependencies

### ISSUE THREAD

**Issue by codevonnie** [Rabhimself/goEatAPI#12]
We need to add dependencies to Vendor folder for Go and Facebook so the app will compile on Heroku.  Required dependencies are:

gopkg.in/mgo.v2
github.com/huandu/facebook

**Comment by Rabhimself** [comment]
I've got the mongo stuff added, but that facebook library is being a pain.

**Comment by Rabhimself** [comment]
There was something wrong with the huandu entry in the godeps file. I deleted the package from my gopath and the godeps.json, ran a /go get/ & /godep save/, it's deploying now.
