### ISSUE TITLE
Facebook Unsafe Scripts

### ISSUE THREAD

**Issue by arnoldout** [Rabhimself/goEatAPI#2]
Most browsers are blocking the facebook login button due to "unsafe scripts"

**Comment by codevonnie** [comment]
Did you get this sorted Oliver?

**Comment by arnoldout** [comment]
Not yet, but for now, as a workaround you should be able to allow the scripts by clicking the icon in the address bar

**Comment by arnoldout** [comment]
Using HTTPS has fixed this error
